# literate-tools
All the sources required to tangle code and create html docs

* Setup Emacs for Incremental Build
  
  1. When tangling inline, using =C-v t=, indentation maight not be preserved.
     To ensure indentation is preserved, add the following line to the emacs
     initialization file. Most probably it will =~/.emacs=

     #+BEGIN_EXAMPLE
     (setq org-src-preserve-indentation t)
     #+END_EXAMPLE

  2. To enable faster build, add the following line to the same initialization
     file
     #+BEGIN_EXAMPLE
     (defvar org-babel-use-quick-and-dirty-noweb-expansion t
     "Set to true to use regular expressions to expand noweb references.
     This results in much faster noweb reference expansion but does
     not properly allow code blocks to inherit the \":noweb-ref\"
     header argument from buffer or subtree wide properties.")
     #+END_EXAMPLE

  3. Copy the following files from =elisp= directory to =~/.emacs.d/custom= directory

     #+BEGIN_EXAMPLE
     cd.el
     dired-operations.el       
     incr-build.el             
     tangle-with-publish-dir.el
     #+END_EXAMPLE

  4. Make the following changes to your =.emacs= file

     #+BEGIN_EXAMPLE
     (require 'cl)
     ;;; dired
     ;;; =====
     ;; for changing to the directory of the buffer in shell
     (load "~/.emacs.d/custom/cd")
     (load "~/.emacs.d/custom/dired-operations")
     (load "~/.emacs.d/custom/incr-build")
     (load "~/.emacs.d/custom/tangle-with-publish-dir")

     (require 'incr-build)
     (setq dired-dwim-target t)
     (setq dired-copy-preserve-time t)
     (setq dired-recursive-copies 'top)

     (define-key dired-mode-map "b" 'browse-url-of-dired-file)
     (load "dired-x")
     (define-key dired-mode-map "z" 'dired-remote-copy)
     (define-key dired-mode-map "r" 'rsync-se-101)
     (define-key dired-mode-map "\C-ca" 'dired-acroread-file)
     (define-key dired-mode-map "\C-cd" 'cd-buffer-dir)
     #+END_EXAMPLE

* Build Incrementally
  Incremental copying and tangling of org files to build directory 

  1. In dired mode use key P to push files code files to
     build/code directory.
     #+BEGIN_EXAMPLE
     If you are in dired mode in directory prj/src and mark 
     the files
     prj/src/file1.py and
     prj/src/file2.py
     and then hit P, they get copied to prj/build/code
     #+END_EXAMPLE

  2. Alternatively, from dired mode, use key T to tangle org
     files and push the tangled code to build/code directory

     #+BEGIN_EXAMPLE
     If you are in dired mode in directory prj/src and mark
     file1.org and file2.org, and these files tangle out file1.py and file2.py
     then hit T, they get copied to 

     They get copied to 
     prj/build/code/file1.py
     prj/build/code/file2.py

     #+END_EXAMPLE
* readtheorg
  We moved in files from [[https://github.com/fniessen/org-html-themes][read-the-org]] to have another
  styling for document publishing.
